version: '3.4'

services:
  influxdb:
    image: influxdb:1.8.5
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana:/var/lib/grafana

volumes:
  influxdb:
    external: false
  grafana:
    external: false

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
